user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

roomrent:
    resource: "@RoomrentBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
